source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               libs/,\
               license.txt,\
               build.properties,\
               plugin.xml,\
               libs/jackson-annotations-2.13.0-rc1.jar,\
               libs/jackson-core-2.13.0-rc1.jar,\
               libs/jackson-databind-2.13.0-rc1.jar
src.includes = src/,\
               META-INF/,\
               plugin.xml,\
               license.txt,\
               source.. = src/
jars.compile.order = .,\
                     lib/
